services:
  ollama:
    container_name: grampi_ollama
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped

  webui:
    container_name: grampi_webui
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    ports:
      - 8080:8080
    volumes:
      - webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - "OLLAMA_BASE_URL=http://ollama:11434"
      - "WEBUI_SECRET_KEY="
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  webui: {}
