services:
  ollama:
    container_name: grampi_ollama
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ollama --version || exit 1
    command: serve

  webui:
    container_name: grampi_webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - webui:/app/backend/data
    depends_on:
      - ollama

volumes:
  ollama:
  webui:
